region: us
version: '2'
authtoken: 2R99OgD0ePI32nZUM3rtKTRI6ve_rSwr6EhxMFLq1WTyETNm
tunnels:
  twilio-app:
    addr: 127.0.0.1:8001
    proto: http
  plivo-app:
    addr: 127.0.0.1:8002
    proto: http
  bolna-app:
    addr: 127.0.0.1:5001
    proto: http
